### ISSUE TITLE
Object Visitor for File Responses

### ISSUE THREAD

**Issue by jonmeyerson** [Azure/azure-functions-openapi-extension#136]
I'm trying to return a file response from an Azure Function in the OpenApi format  https://swagger.io/docs/specification/describing-responses - Response That Returns a File

I think the following would be the syntax to indicate a jpeg response.
`[OpenApiResponseWithBody(HttpStatusCode.OK, "image/jpeg", typeof(byte[])]`

```
        '200':
          description: A File
          content:
            image/jpeg:
              schema:
                type: string
                format: binary
```

What am am seeing is:
```
         "200": {
            "description": "Payload of Array of Byte",
            "schema": {
              "type": "array"
            }
          }
```
This resolves as an error in the SwaggerUI rendering. 

I've taken a look at the source and don't see a Object Visitor defined that can return format binary.

This seems to be related to https://github.com/Azure/azure-functions-openapi-extension/issues/96 and https://github.com/Azure/azure-functions-openapi-extension/issues/97
