### ISSUE TITLE
Property descriptions of models

### ISSUE THREAD

**Issue by josmithua** [Azure/azure-functions-openapi-extension#14]
Hi there,

First off, this is a super great project and I'm glad it's being developed!

I'm trying it one of my projects and I was wondering (maybe its a question for the main .NET OpenAPI package) if there is a way to add property descriptions to the open api output.

For example, say I have a model:

```cs
class UserResponse
{
    public string Name { get; set; }
    public string Id { get; set; }
}
```

When I specify 

```cs
[OpenApiResponseWithBody(HttpStatusCode.OK, "application/json", typeof(UserResponse)]
```

I would like to have it output

```yaml
  UserResponse:
    type: object
    properties:
      Name:
        type: string
        description: The name of the user
      Id:
        type: string
        description: The id of the user (GUID)
```

Is there any attributes I can add to the model to give the properties descriptions and have them included in the output?

Thanks!
