### ISSUE TITLE
Feature request: Mark property as deprecated

### ISSUE THREAD

**Issue by josmithua** [Azure/azure-functions-openapi-extension#319]
The OpenAPI spec supports a `deprecated` flag on schema properties:
```yaml
UserResponse:
    type: object
    properties:
      Nme:
        type: string
        description: The name of the user
        deprecated: true
      Name:
        type: string
        description: The name of the user
      Id:
        type: string
        description: The id of the user (GUID)
```

It would be great if the `OpenApiPropertyAttribute` had a parameter to support this. For example:
```csharp
class UserResponse
{
    [OpenApiProperty(Description = "The name of the user", Deprecated = true)]
    public string Nam { get; set; }

    [OpenApiProperty(Description = "The name of the user")]
    public string Name { get; set; }

	[OpenApiProperty(Description = "The id of the user (GUID)")]
    public string Id { get; set; }
}
```
