### ISSUE TITLE
GitHub Action to Generate OpenAPI Document within CI/CD Pipeline

### ISSUE THREAD

**Issue by justinyoo** [Azure/azure-functions-openapi-extension#369]
**Describe the issue**

We need a GitHub Action to generate the OpenAPI document on-the-fly after building an Azure Functions app within a CI/CD pipeline.

**Additional context**

Related to #366 

There are many requests for a CLI to auto-generate the OpenAPI document, which is mainly for the CI/CD pipeline use. But it's technically possible for those auto-generation within this context.

Similar approach has already been applied to this repo's GitHub Actions workflow:

https://github.com/Azure/azure-functions-openapi-extension/blob/e432a6bcdcd6f060f8a0cc58db680066f20157cb/.github/workflows/main-build.yaml#L77-L108

**Comment by davidpetric** [comment]
This solution is good only if your project contains HttpTriggers.

If you have also ServiceBusTriggers or TimerTriggers, when the azure function starts will start to log/throw errors in console because the functions try to make real connections to Service Bus, Azure Storage. 

This will result in pipeline becoming flaky and start to fail depending of the number of your functions, because it tries to connect 5 times to the Azure Functions then pipeline fails because of the errors.
ServiceBusTrigger will show errors like:
Attempt 1 of 5 failed: Unable to connect to the remote server
Waiting for 12 seconds before retrying...
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.


Azure Function isn't helping us either, I've tried all sort of stuff to disable programmatically ServiceBusTriggers and TimerTriggers and ended up having to disable each function individually using environment variables for the task in pipeline, like in the following example.

```
- task: PowerShell@2
displayName: Create swagger json
env:
    AzureWebJobs.ActivityTopicServiceBusTrigger1.Disabled: true
    AzureWebJobs.ActivityTopicServiceBusTrigger2.Disabled: true
    AzureWebJobs.ActivityTopicServiceBusTrigger3.Disabled: true
    AzureWebJobs.ActivityTopicServiceBusTrigger4.Disabled: true
    AzureWebJobs.ActivityTopicServiceBusTrigger5.Disabled: true
    Force: true
inputs:
    filePath: '$(Build.SourcesDirectory)/Build/Get-OpenApiDocument.ps1'
    arguments: '-FunctionAppPath "$(Build.SourcesDirectory)/Src/ExternalServices/Fix.Api" -OutputPath "$(System.DefaultWorkingDirectory)/Deploy/Pm.PreDeployment/swagger" -BaseUri http://localhost:7071/api/ -Endpoint openapi/v3.json -OutputFilename "-openapi.json" -UseWindows'
    workingDirectory: '$(Build.SourcesDirectory)/Build'
```

But this is not ideal because when we add a new ServiceBusTrigger or TimerTigger we will need to add it there.
