### ISSUE TITLE
Action doesn't run .net 6 function successfully

### ISSUE THREAD

**Issue by TomCharman** [Azure/azure-functions-openapi-extension#675]
**Describe the issue**
From about 24 hours ago, we've been seeing the following error across multiple repositories when running this extension with a .net 6 function. This is similar to a warning we used to see in the logs, but now it seems to be blocking the action from running the function and generating the swagger document. I believe we're using all the options available, and I couldn't find a note about the below.

```
Select a number for worker runtime:
1. dotnet (isolated worker model)
2. dotnet (in-process model)
3. node
4. python
5. powershell
6. custom
Invoke-RestMethod: /entrypoint.ps1:55
Line |
  55 |  Invoke-RestMethod -Method Get -uri $requestUri | ConvertTo-Json -Dept …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Connection refused
```

The previous warning was
```
Can't determine project language from files. Please use one of [--dotnet-isolated, --dotnet, --javascript, --typescript, --java, --python, --powershell, --custom]
```

**To Reproduce**
1. Run the extension on a .net 6 azure function project using action as per below
2. Observe no file is generated
3. Check logs in GitHub and see warning above

```
      - name: Generate OpenAPI document
        id: oai
        uses: Azure/azure-functions-openapi-extension/actions/build-openapi@v1
        with:
          functionAppPath: "./MyFunction.Functions/bin/Release/net6.0"
          requestUri: "http://localhost:7071/api/openapi/v3.json"
          documentPath: "generated"
          documentName: "swagger.json"
          delay: "30"
          isRemote: "false"
```

**Expected behavior**
As was happening two days ago, would expect the action to generate a swagger document.

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment (please complete the following information, if applicable):**
 - GitHub Actions
 - Version 1
